### ISSUE TITLE
Feature - Reject wallet name collision on injection

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#10]
In https://github.com/fabianbormann/cardano-peer-connect/issues/4 we agreed on that wallets need to inject into `window.cardano.[walletname]-p2p`.

To make it easier for developers, we must implement a warning that injecting into an existing namespace should trigger an error.

**Comment by marcuspuchalla** [comment]
Add PR https://github.com/fabianbormann/cardano-peer-connect/pull/11

**Comment by fabianbormann** [comment]
Solved by merging PR #11
