### ISSUE TITLE
Fix typo in splice call

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#2]
There is a small typo in https://github.com/fabianbormann/cardano-peer-connect/blob/main/index.ts#L260 when calling the cip30 injected functions. It shall use splice, not slice.

**Comment by marcuspuchalla** [comment]
This pr fixes it https://github.com/fabianbormann/cardano-peer-connect/pull/3

**Comment by fabianbormann** [comment]
Thx :) & merged
