### ISSUE TITLE
Feature request - Add experimental

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#20]
As specified in [CIP30](https://cips.cardano.org/cips/cip30/#experimentalapi) we should add injecting the experimental API that a wallet can provide. 

This would also make the implementation on par with the normal dApp Web bridge.

**Comment by marcuspuchalla** [comment]
It was more work to get it working as needed, but here is the PR. https://github.com/fabianbormann/cardano-peer-connect/pull/22 😄 

The commit and the newly created classes have a lot of text explaining what is happening. 

Basically, I create a blueprint of the properties and functions that a wallet wants to inject and convert into a format easily shared between different systems. The DApp can then use this blueprint to interact with the wallet as if it had direct access.

All new functions can be already used with the demo implementation, see https://github.com/fabianbormann/cip-0045-demo-implementation/pull/2

**Comment by fabianbormann** [comment]
Thx @marcuspuchalla the PR has been reviewed and merged 👍
