### ISSUE TITLE
Feature Request: Bidirectional Auto-Connect for Seamless Wallet-DApp Integration

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#21]
Enhance P2P connector lib with a bidirectional auto-connect feature, enabling seamless wallet-DApp integration regardless of the order they're opened.

Key improvements:

- Add a configurable auto-connect option to the DAppPeerConnect instance (enabled by default).
- Automatically attempt connection to the most recently connected wallet.
- Allow specifying an alternative wallet address if needed.

**Comment by fabianbormann** [comment]
@marcuspuchalla has all of this been covered by #27 ? 😊

**Comment by marcuspuchalla** [comment]
> @marcuspuchalla have all of this been covered by #27 ? blush

Yes, it includes all the changes required for this to work.

A second meerkat on the wallet side is created. The address is sent to the DApp on the first successful connection. After that point, the DApp can connect to this Meerkat instance, signaling that it has started and that the wallet can initiate a regular connection.

**Comment by fabianbormann** [comment]
Nice sounds good 😊
