### ISSUE TITLE
Feature - Allow for fast api switch

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#33]
Most wallet apps provide access to multiple wallets. When a user wants to switch to a different wallet when already being connected to a DApp, at the moment, he had to disconnect and reconnect for the new wallet to get injected.

In https://github.com/fabianbormann/cardano-peer-connect/pull/32 I extracted the inject function and made it public so a connected client can specify that he wants to inject another api and overwrite the existing one. This makes changing the API a lot easier and more reliable.

**Comment by fabianbormann** [comment]
Perfect thank you for the explanation 👍 💯  done by merging #32
