### ISSUE TITLE
Make address in IDAppInfos not optional

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#41]
The address of a DApp should be a requirement and not optional in IDAppInfos. 

Therefore I propose we change the constructor signature of DAppPeerConnect to only take `name` and `url` as IDAppInfos. Because a DApp cannot know its address at the start. It will only know its address if it provides a seed; in this case, the address would be redundant information in the constructor.

Later on, we set the address from the created meerkat instance automatically.
When using the IDAppInfos interface, one would not have to check if the property exists and can rely on that information.

**Comment by fabianbormann** [comment]
done by merging #42 🎉
